[package]

name = "cssparser"
version = "0.1.1"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "Rust implementation of CSS Syntax Level 3"
documentation = "http://servo.github.io/rust-cssparser/cssparser/index.html"
repository = "https://github.com/servo/rust-cssparser"
readme = "README.md"
keywords = ["css", "syntax", "parser"]
license = "MPL2"


[dependencies]
encoding = "0.2"
